title: Website Verification System
email: deantech1980@gmail.com
description: A proposal for a website verification system.
baseurl: "/Website-Verification-System"
url: "https://deantech1980.github.io"
author:
  name: Dean John Weiniger
  email: deantech1980@gmail.com
plugins:
- jekyll-remote-theme
- jekyll-seo-tag
- jekyll-sitemap
remote_theme: pages-themes/cayman@v0.2.0
